### ISSUE TITLE
Ways to change styling of containing div

### ISSUE THREAD

**Issue by Mattasher** [socialtables/react-user-tour#26]
How can we change the style for the main containing box, in particular, height, width, and background color of the box and arrow?

**Comment by conorhastings** [comment]
The absolutely positioned main box, can be styled using the style prop. The arrow currently takes an `arrowSize` and `arrowColor` prop. Alternatively you can use the `arrow` prop to pass in your own arrow component.

For the overall container of the component, I've added a `containerStyle` prop. 

Let me know if this helps.

-Conor

**Comment by Mattasher** [comment]
Excellent thanks!
