### ISSUE TITLE
Content is blurring because of decimal numbers in css transform

### ISSUE THREAD

**Issue by floschie** [socialtables/react-user-tour#34]
Hey there,

the plugin works fine. Thanks a lot! :) However the placement of the react-user-tour-container insides is calculated in decimal numbers (eg. transform: translate3d(146.5px, 164px, 0px)) so it causes blurring of the actual content inside in Chrome on non Retina displays.

Is there a way to round the calculated placement so it would use CSS translate with whole pixels only?

Thanks,
Florian

**Comment by conorhastings** [comment]
@floschie sure, we could probably use Math.floor or Math.ceil , feel free to make a PR, not sure when i'll have time to get it

**Comment by conorhastings** [comment]
published `v2.5.0`

**Comment by floschie** [comment]
thanks conor!
