### ISSUE TITLE
Dynamic Usage

### ISSUE THREAD

**Issue by vivekparekh8** [socialtables/react-user-tour#37]
I am trying to write a component with ```<UserTour/>``` which I import once in the application and then give class selectors to the divs with which I want to attach the popovers, But it doesn't seem to work.
Looking for some insight.
Thank you.
My component render returns below piece.
```
<div style={{ position: 'absolute', top: 0 }}>
				<Tour
					active={this.state.isTourActive}
					step={this.state.tourStep}
					onNext={(step) => this.setState({tourStep: step})}
					onBack={(step) => this.setState({tourStep: step})}
					onCancel={() => this.setState({isTourActive: false})}
					steps={[
						{
					    step: 1,
							selector: '.stop-1',
							title: <div style={{color: 'blue'}}>My Web</div>,
							body: <div style={{color: 'green'}}>Site</div>
						},
						{
							step: 2,
							selector: '.stop-2',
							title: <div style={{color: 'blue'}}>Wow</div>,
							body: <div style={{color: 'yellow'}}>so good</div>
						}
					]}
				/>
			</div>
```

I use className='stop-1' with some div like 
```
<div
        className='stop-1'
        style={{position: 'fixed', bottom: '10px', right: '10px'}}
      >
```

But that doesnot work. It doesnot show popover attached to that particular div. but shows on top where i Imported and used it

**Comment by conorhastings** [comment]
@vivekparekh8 what is the default state of isTourActive, it is likely the div it is trying to attach to does not exist yet. if it defaults to true i would reccomend defaulting to false and setting to true in componentDidMount

**Comment by vivekparekh8** [comment]
just trying it out. Thanks for quick reply.
